language: "haskell"
install:
      - "cabal install --dependencies-only --enable-tests"
      - "cabal configure --enable-tests"
      - "cabal build"
      - "cabal test"
      - "cabal install"
notifications:
    email: true
